import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Prototype imagery ships as our own generated SVG placeholders.
    // Safe here because every SVG is first-party (generated by
    // scripts/gen-media.mjs), never user-supplied. Swap for webp/avif
    // raster assets and this can be removed.
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    formats: ["image/avif", "image/webp"],
  },
};

export default nextConfig;
